#!/bin/bash
# Generates hashes for MediaWiki extensions and skins for a given MediaWiki version.
# Requires Nix, nix-prefetch-git, and jq.
set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <tag> <output>"
    exit 1
fi

TAG="$1"
OUTPUT="$2"

MW_DATA="$(nix-prefetch-git https://github.com/wikimedia/mediawiki.git "$TAG")"
MW_REV="$(echo "$MW_DATA" | jq -r .rev)"
MW_HASH="$(echo "$MW_DATA" | jq -r .hash)"

MW_DOTGIT_DATA="$(nix-prefetch-git https://github.com/wikimedia/mediawiki.git "$TAG" --leave-dotGit)"
GIT_DIR="$(echo "$MW_DOTGIT_DATA" | jq -r .path)/.git"
export GIT_DIR
(
    echo "# DO NOT EDIT THIS FILE! It is generated by genmwhashes.sh"
    echo "# Command: genmwhashes $TAG $OUTPUT"
    echo "{"

    echo "  mediawiki.name = \"mediawiki\";"
    echo "  mediawiki.tag = \"$TAG\";"
    echo "  mediawiki.rev = \"$MW_REV\";"
    echo "  mediawiki.hash = \"$MW_HASH\";"

    git ls-tree HEAD extensions/ skins/ | grep commit | while read -r line; do
        unset GIT_DIR
        SUBDIR=$(echo "$line" | awk '{print $4}')
        TYPE=$(cut -d'/' -f1 <<< "$SUBDIR")
        REPO=$(cut -d'/' -f2 <<< "$SUBDIR")
        COMMIT=$(echo "$line" | awk '{print $3}')
        HASH=$(nix-prefetch-git "https://github.com/wikimedia/mediawiki-$TYPE-$REPO.git" "$COMMIT" | jq -r .hash)
        echo "  $TYPE.$REPO.name = \"$REPO\";"
        echo "  $TYPE.$REPO.rev = \"$COMMIT\";"
        echo "  $TYPE.$REPO.hash = \"$HASH\";"
    done

    echo "}"
) > "$OUTPUT"
