apiVersion: 1
groups:
- orgId: 1
  name: NodeRules
  folder: Root
  interval: 5m
  rules:
  - uid: a34f2752-193a-4b2a-b3d9-09f7ed8807d7
    title: DiskAvailableBelowThreshold
    condition: MinThreshold
    data:
    - refId: DiskAvail
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: prometheusDataSource
      model:
        datasource:
          type: prometheus
          uid: prometheusDataSource
        editorMode: code
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: DiskAvail
    - refId: MinThreshold
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
        - evaluator:
            params:
            - 0.15
            type: lt
          operator:
            type: and
          query:
            params: []
          reducer:
            params: []
            type: avg
          type: query
        datasource:
            name: Expression
            type: __expr__
            uid: __expr__
        expression: DiskAvail
        hide: false
        refId: MinThreshold
        type: threshold
    noDataState: NoData
    execErrState: Error
    for: 5m
    labels: {}
    isPaused: false
  - uid: d1563530-a1ac-4fe6-8103-e4751f49fa16
    title: MemoryAvailableBelowThreshold
    condition: MinThreshold
    data:
    - refId: MemAvail
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: prometheusDataSource
      model:
        datasource:
          type: prometheus
          uid: prometheusDataSource
        editorMode: code
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: MemAvail
    - refId: MinThreshold
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
        - evaluator:
            params:
            - 0.15
            type: lt
          operator:
            type: and
          query:
            params: []
          reducer:
            params: []
            type: last
          type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: MemAvail
        intervalMs: 1000
        maxDataPoints: 43200
        refId: MinThreshold
        type: threshold
    noDataState: NoData
    execErrState: Error
    for: 5m
    labels: {}
    isPaused: false
