apiVersion: 1
groups:
- orgId: 1
  name: NodeRules
  folder: Root
  interval: 5m
  rules:
  - uid: a34f2752-193a-4b2a-b3d9-09f7ed8807d7
    title: DiskWillFillIn1Day
    condition: A
    data:
    - refId: A
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: prometheusDataSource
      model:
        datasource:
          type: prometheus
          uid: prometheusDataSource
        editorMode: code
        expr: predict_linear(node_filesystem_free_bytes{job="nodes", mountpoint="/"}[1h], 24 * 3600) < 0
        hide: false
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
    noDataState: OK
    execErrState: Error
    for: 30m
    annotations: {}
    labels: {}
    isPaused: false
  - uid: d1563530-a1ac-4fe6-8103-e4751f49fa16
    title: MemoryAvailableBelowThreshold
    condition: C
    data:
    - refId: A
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: prometheusDataSource
      model:
        datasource:
          type: prometheus
          uid: prometheusDataSource
        editorMode: code
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
    - refId: C
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
        - evaluator:
            params:
            - 0.15
            type: lt
          operator:
            type: and
          query:
            params:
            - C
          reducer:
            params: []
            type: last
          type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: C
        type: threshold
    noDataState: NoData
    execErrState: Error
    for: 5m
    labels: {}
    isPaused: false
